name: Run Cypress Tests (dependabot)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_DIALECT: ${{ secrets.CYPRESS_DIALECT }}
      baseUrl: ${{ secrets.CYPRESS_BASE_URL }}
      container: cypress/browsers:node-22.18.0-chrome-139.0.7258.138-1-ff-142.0-edge-139.0.3405.102-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/main.spec.cy.ts
          install: npm ci
          start: npm run build && serve -s build