name: Fv-Apps-Deploy
on:
  workflow_run:
    workflows: [Fv-Apps-Tests]
    types: 
        - completed
jobs:
  inspect_changes:
    environment: preprod
    name: Inspect Infra Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: uploads
          path: downloads/
      - name: Check directory files
        run: |
         ls
         mv downloads/build modules/build
         cd modules
         ls
         cd build
         ls
         cd ../..
      - name: Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
         cd modules
         terraform init -lock=false
         terraform fmt
         terraform plan
  update_infra_changes:
    name: Update Infra and App Changes
    runs-on: ubuntu-latest
    needs: inspect_changes
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: uploads
          path: downloads/
      - name: Check directory files
        run: ls; mv downloads/build modules/build; cd modules; ls; cd build; ls; cd ../..
      - name: Terraform plan and apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: cd modules; terraform init -lock=false; terraform fmt; terraform plan; 
        #terraform apply -auto-approve -lock=false